[package]
name = "ccperf-mvfst"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"

[dependencies]
structopt = "0.2"
failure = "0.1"

[build-dependencies]
bindgen = "0.49"
